on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
<<<<<<< HEAD:.github/workflows/build.yml
      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.0
        with:
          # Defining all the required inputs
          # I used the mono version of Godot in this example
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_export_templates.tpz
          cache: true
          # set this either to . or your game path, e.g. ./godot in case
          # your game is within a sub-directory
          relative_project_path: ./
          relative_export_path: ./build
          archive_output: true
          use_godot_3: true
          
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: create release
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ secrets.GH_CREDENTIALS }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action     
=======
      - name: create game release
        uses: firebelley/godot-export@v3.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/mono/Godot_v3.5.2-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/mono/Godot_v3.5.2-stable_mono_export_templates.tpz
          relative_project_path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
>>>>>>> dab37f8bd20afff2cc90b6eb8c8c74497e1dd94e:.github/workflows/create-release.yml
