on:
  release:
    types: [published]

jobs:
  release_web:
    runs-on: ubuntu-latest
    steps:
      - name: download Web
        id: download-web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: hunted-web.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: hunted-web
          ITCH_USER: nephas
          PACKAGE: hunted-web.zip
          VERSION: ${{ steps.download-web.outputs.version }}  
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: hunted-win.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: hunted-web
          ITCH_USER: nephas
          PACKAGE: hunted-win.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: hunted-linux.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Linux)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: hunted-web
          ITCH_USER: nephas
          PACKAGE: hunted-linux.zip
          VERSION: ${{ steps.download-linux.outputs.version }}
